ad=input("Adınızı Giriniz:")
sad=input("Soyadınızı Giriniz:")
vz=int(input("Vize notunuzu giriniz:"))
fn=int(input("Final notunuzu giriniz:"))
print("Adınız:",ad)
print("Soyadınız:",sad)
print("Vizeniz:",vz)
print("Finaliniz:",fn)
print("Ortalamanız: ",vz*0.40+fn*0.60)
